- Cargo.toml
> Increment version for crates.io

- Cargo.toml
- LICENSE-APACHE
Note that the badge on the README won't update until the next time the version is updated on crates.io.
> Add Apache-2.0 license option for full compatability with the Rust project license

- Cargo.toml
This makes sure the libc dependency for this crate is the same as coreaudio-sys', which fixes the build after some recent libc changes.
> Updated coreaudio-sys and libc versions

- .travis.yml
Also added beta and nightly builds to the "allowed failures" list. This just helps us stay ahead of the curve in terms of potentially breaking changes with future version of rust and/or the libs we depend on.
None of the code is changed, so no need to publish with just this change.
> Updated travis config to test beta again

- examples/sine.rs
- src/audio_unit/mod.rs
- src/audio_unit/stream_format.rs
I have a few other breaking changes in mind, so I think I'll do them before publishing a new  version.
> Improve APIs of both AudioUnit and StreamFormat types.

- Cargo.toml
- src/audio_unit/mod.rs
- src/audio_unit/types.rs
Closes #34.
Also moved the various `Type`s into their own module.
Will merge and publish this as **0.4.0** when travis passes.
> Added AudioUnit::set_property/get_property methods. Use them to simplify other methods.

- Cargo.toml
- examples/sine.rs
- src/audio_unit/audio_format.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
- src/lib.rs
This removes the artificial lifetimes imposed on the `render_callback::Args` and `NonInterleaved` types. These were originally added to ensure that the args or buffer never outlived the scope of the callback, however this was under the incorrect assumption that the callback was "push"ing for data and not "pull"ing which is actually the case.
Replaces the `ActionFlags` field of the `render_callback::Args` with an `action_flags::Handle` type which more correctly represents the behaviour of the original coreaudio API. This type allows the callback to provide various "hint"s to the audio unit. As a result, `render_callback::Args` is no longer `Clone` or `Copy`, however this shouldn't be much of an issue.
Send is now implemented for `NonInterleaved` and `AudioUnit`.
> [Breaking Change] Remove unnecessary lifetimes. Add `action_flags::Handle` type. Update to bitflags 0.7.

- .travis.yml
Ivan Vyshnevskyi kindly took the time to point out that the auth token
for this repo has been leaked.
This PR adds a regenerated token along with an adjustment to the
.travis.yml that should avoid future leaks.
This is the same issue as PistonDevelopers/image#596.
Ivan will be releasing a blog post on how he discovered the issue soon.
Will link to it as soon as it is available!
> Regenerate Github Auth Token

- src/audio_unit/types.rs
iOS provides three I/O (input/output) units. The vast majority of audio-unit applications use the Remote I/O unit, which connects to input and output audio hardware and provides low-latency access to individual incoming and outgoing audio sample values. For VoIP apps, the Voice-Processing I/O unit extends the Remote I/O unit by adding acoustic echo cancelation and other features. To send audio back to your application rather than to output audio hardware, use the Generic Output unit.
See https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/AudioUnitHostingGuide_iOS/UsingSpecificAudioUnits/UsingSpecificAudioUnits.html
> Add Remote I/O unit for ios

- Cargo.toml
- src/audio_unit/audio_format.rs
- src/audio_unit/render_callback.rs
- src/audio_unit/sample_format.rs
- src/audio_unit/stream_format.rs
See #54.
Also updates to bitflags v1.0 which moves the flags from modules to associated types on their respective flag types.
`LinearPCMFlags` was renamed to `LinearPcmFlags` in order to follow rust's camel-case abbreviation conventions more closely.
cc @matwork I just realised that #54 is a breaking change due to rust's exhaustive matching so I've bumped this to 0.7 instead :+1:
> Publish 0.7 for addition of Remote I/O unit for iOS

- Cargo.toml
- src/audio_unit/audio_format.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
- src/audio_unit/stream_format.rs
- src/error.rs
- src/lib.rs
See RustAudio/coreaudio-sys#4 for more details.
Also add's some missing `Scope` variants and fixes their enumeration order.
Removes the dependency on libc in favour of `std::os::raw`.
Publish 0.8 for the breaking change.
> Update to coreaudio-sys 0.2. Rename reexport from bindings to sys. Publish 0.8.

- Cargo.toml
- src/lib.rs
An optional feaure per framework is now provided for more granular
control over the framework linking.
Note that at last one feature must be enabled at all times or
coreaudio-sys and coreaudio-rs will fail to compile.
> Add optional features to match those offered by coreaudio-sys

- Cargo.toml
- examples/sine.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
An AudioUnit that is setup for input streams can now receive data by
calling `set_input_callback`.
This also updates some of the other `AudioUnit` methods to no longer
assume output streams.
Publish **0.9** with breaking changes related to input support.
>  Add support for AudioUnits with input streams 

- Cargo.toml
- src/audio_unit/render_callback.rs
This happened to work in the past as in many cases the input stream will
have less than or equal to the same number of channels as the output
stream.
Will publish this as 0.9.1.
> Fix bug where input stream buffer was created using output stream format

- .travis.yml
- examples/feedback.rs
- examples/ios/Cargo.toml
- examples/ios/build_rust_deps.sh
- examples/ios/coreaudio-ios-example.xcodeproj/project.pbxproj
- examples/ios/coreaudio-ios-example.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- examples/ios/coreaudio-ios-example.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- examples/ios/ios-src/AppDelegate.h
- examples/ios/ios-src/AppDelegate.m
- examples/ios/ios-src/Base.lproj/LaunchScreen.storyboard
- examples/ios/ios-src/Base.lproj/Main.storyboard
- examples/ios/ios-src/Info.plist
- examples/ios/ios-src/ViewController.h
- examples/ios/ios-src/ViewController.m
- examples/ios/ios-src/main.m
- examples/ios/src/feedback.rs
- examples/ios/src/lib.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
Fixes https://github.com/RustAudio/coreaudio-rs/issues/67
I started at https://github.com/bevyengine/bevy/issues/87 and ended up here
Some prior discussion in https://github.com/RustAudio/coreaudio-rs/pull/69
This enables building for iOS `aarch64-apple-ios` and `x86_64-apple-ios` and I managed to get audio playback on device and simulator via rodio/cpal. The actual change here affects the mic recording callback so I decided to write a feedback example app for manual testing.
Manually tested microphone + playback works on iOS
There seem to be some differences between macOS and iOS CoreAudio, in that the iOS can only enable mic recording on an uninitialized AudioUnit. Similarly the iOS one requires an active AVAudioSession to do some operations like reading out the current hardware buffer …
> Fix iOS compilation error and add macOS + iOS feedback example applications

- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
- src/error.rs
- dyn trait
- try!
- mem::uninitialized
Not sure if I'm doing this right. macOS feedback example still runs though.
> Fix deprecation warnings

- src/audio_unit/render_callback.rs
vec! can make use of calloc to initialize buffer in a identically fast and safer way.
Here's the usual [go-to reference](https://github.com/rust-lang/rust/issues/54628) for all your doubts.
Also the original code had these operations interleaved operations on the Vec with other constructions which seems mysterious, be careful when reviewing and auditing.
> Initialize buffers with zero-fill

- Cargo.toml
I'm assuming I've done the version bump right. My iOS change tweaked the input/render callbacks scope/elements so I'd rather play it safe and call it a breaking change. Would prefer not to accidentally cause breakages by people running `cargo update`.
> Publish 0.10.0

- .github/workflows/coreaudio-rs.yml
This fixes it, but I don't understand why it is necessary. `ONLY_ACTIVE_ARCH=YES` didn't work, supposedly it should only build for x86_64 simulator with that on.
> Fix iOS CI

- Cargo.toml
- examples/feedback.rs
- examples/feedback_interleaved.rs
- examples/sine_advanced.rs
- src/audio_unit/macos_helpers.rs
This adds two new helpers for managing hog mode (exclusive access).
> Add helpers for hog mode

- Cargo.toml
To release https://github.com/RustAudio/coreaudio-rs/pull/91
> Bump crate version to 0.11.2

- src/audio_unit/stream_format.rs
- src/audio_unit/types.rs
Fix for the following warnings::
```
warning: unclosed HTML tag `S`
--> src/audio_unit/stream_format.rs:19:35
|
19 | /// `bytes_per_packet` = size_of::<S>()
|                                   ^^^
|
= note: `#[warn(rustdoc::invalid_html_tags)]` on by default
help: try marking as source code
|
19 | /// `bytes_per_packet` = `size_of::<S>`()
|                          +            +
warning: unclosed HTML tag `S`
--> src/audio_unit/stream_format.rs:20:34
|
20 | /// `bytes_per_frame` = size_of::<S>()
|                                  ^^^
|
help: try marking as source code
|
20 | /// `bytes_per_frame` = `size_of::<S>`()
|                         +            +
warning: unclosed HTML tag `S`
--> src/audio_unit/stream_format.rs:22:35
|
22 | /// `bits_per_channel` = size_of::<S>() / …
```
> Fix of 4 documentation warnings

- Cargo.toml
- examples/sine_advanced.rs
- src/audio_unit/macos_helpers.rs
- src/error.rs
Added  `get_audio_device_ids_for_scope` which returns devices that are listed under a specific scope instead of just global and `get_audio_device_supports_scope` which checks if a specific devices has any channels for a scope.
This is basically a cleanup of https://github.com/RustAudio/coreaudio-rs/pull/94
> Add support for scope related queries

- .github/workflows/coreaudio-rs.yml
- Cargo.toml
- src/audio_unit/macos_helpers.rs
I felt like doing a follow up to #96.
> Added unit tests for get_audio_device_ids and bump version to 0.11.3

- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
Getting input from a microphone needs to use the Output scope and Input Element, and sending audio to a speaker needs to use the Input Scope and Output Element. See Figure 1-3 in https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/AudioUnitHostingGuide_iOS/AudioUnitHostingFundamentals/AudioUnitHostingFundamentals.html
This PR also removes a bit of redundancy in the code by reusing input and output stream functions in the callback code.
> Fix input and output scope and element usage. 

- src/audio_unit/macos_helpers.rs
Some devices (bluetooth headsets for example) show up as two device ids with the same name. One of these supports capture, the other playback. This PR adds an argument to the `get_device_id_from_name` helper function to get the correct device id for capture or playback.
Loosely related to https://github.com/RustAudio/coreaudio-rs/pull/104
> Add argument to search for device by name and scope

- .gitignore
This is to deal with the failed publish ci in https://github.com/RustAudio/coreaudio-rs/actions/runs/8664360312/job/23760589026#step:5:6668 as the new CI checks out LLVM in the project directory.
> Fix publish ci

- src/audio_unit/mod.rs
This patch adds implementations of `AsRef` and `AsMut` for `AudioUnit`, providing access to the underlying `sys::AudioUnit`. This is needed in some cases where functionality is missing from `coreaudio-rs` or when interfacing with other code that requires the underlying `sys::AudioUnit`.
> Add AsRef and AsMut impls for AudioUnit

- Cargo.toml
Release for changes in #121. I ran the changes through [`cargo semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) to be extra sure these aren't breaking changes.
Changes for this bump are for changes from [`19d3388...01ff207`](https://github.com/RustAudio/coreaudio-rs/compare/19d3388...01ff207).
@ori-sky I know it's a little silly but mind giving me a review (or just an approval)? I don't formally need it to merge but like to exercise good practice.
> Bump to 0.12.1

- Cargo.toml
- src/audio_unit/macos_helpers.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
- src/audio_unit/stream_format.rs
- src/error.rs
- src/lib.rs
Use the [`objc2-*`](https://docs.rs/objc2/0.6.0/objc2/topics/about_generated/index.html) crates instead of `coreaudio-sys` (you knew it was coming @simlay 😉):
- `objc2-audio-toolbox`.
- `objc2-core-audio`.
- `objc2-core-audio-types`.
- `objc2-core-midi`.
**Resolves every single [`coreaudio-sys` issue](https://github.com/RustAudio/coreaudio-sys/issues)[^1] and [PR](https://github.com/RustAudio/coreaudio-sys/pulls)** by no longer invoking `bindgen`, and instead generating the headers ahead of time. We should probably deprecate `coreaudio-sys` and archive the repo once this lands.
The bindings generated by `objc2`'s tool `header-translator` are also a bit more type-safe as they include for example nullability information, and is able to merge some enum constants into constants on the enum …
> Use `objc2` crates

- src/error.rs
The current implementation does not include the OSStatus when formatting an unknown error. The number is there but isn't being used. This PR simply includes it in the message. Without this it is very difficult to figure out what goes wrong whenever an error occurs and it's not one of the expected ones.
> Include OSStatus when formatting the Unknown error

- Cargo.toml
- src/audio_unit/audio_format.rs
- src/audio_unit/mod.rs
- src/audio_unit/render_callback.rs
- src/audio_unit/types.rs
- src/error.rs
This library uses quite a few constants, for audio unit types, errors, etc etc. Currently, they are defined directly in the core audio-rs code. But their original definitions are in the sdk headers, and that means they are available in the objc2 crates.
This PR removes all the constant defined in this library, and instead imports them from objc2. This way there Is much less risk for typos, and if there is a typo is much easier to spot. The only exception is the kAudioUnitSubType_RemoteIO subtype which only exists in the iOS sdk. I have not managed to figure out how to import it, so I left this one as it was.
The api almost doesn't change. Only one missing BadData error is added, and some incomplete mapping between os status and error is fixed.
> Import all constants from objc2
